name: Continuous Integration
on: push
jobs:
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build --tag pvdn .
