name: Continuous Integration
on: push
jobs:
  build-without-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python all python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: pip install -e . 
      - name: Run Unittest
        run: python -m unittest discover -s tests -p "*.py"

  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build --tag pvdn .
