name: Continuous Integration
on: push
jobs:
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build --tag pvdn .
